"""
Django settings for wisdar project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from __future__ import absolute_import, unicode_literals
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
WISDAR_DIR = BASE_DIR  # WISDAR_DIR is the same as BASE_DIR in this context

IS_PRODUCTION = os.getenv('DJANGO_PRODUCTION', '').lower() in ['true', '1', 't']

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-@%84#)z)h%nfv!2a7=kh(_5qs3kvog_-bq&bp5ys=%na*eo(!b')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if IS_PRODUCTION:
    ALLOWED_HOSTS = ['wisdar.azurewebsites.net']
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1','wisdar.azurewebsites.net']
    
    
CSRF_TRUSTED_ORIGINS = [
    'https://wisdar.azurewebsites.net',
] if IS_PRODUCTION else ['https://wisdar.azurewebsites.net']


# Application definition

INSTALLED_APPS = [
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]
SITE_ID = 1

if DEBUG:
    INSTALLED_APPS.append('debug_toolbar')  # Add debug_toolbar when DEBUG is True


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Django's default
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if DEBUG:
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')  # Add DebugToolbarMiddleware

ROOT_URLCONF = 'wisdar.urls'
LOGIN_URL = '/login/'
INTERNAL_IPS = [
    '127.0.0.1',
]


TEMPLATE_DIR = os.path.join(WISDAR_DIR, "main/templates")

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wisdar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql' if IS_PRODUCTION else 'django.db.backends.sqlite3',
        'NAME': os.getenv('DBNAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.getenv('DBUSER', ''),
        'PASSWORD': os.getenv('DBPASS', ''),
        'HOST': os.getenv('DBHOST', ''),
        'PORT': os.getenv('DBPORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = 'main.User'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'main/static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email Backend Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'wisdar-auth@outlook.com'
EMAIL_HOST_PASSWORD = '12345678Ww@'

# Default email address 
DEFAULT_FROM_EMAIL = 'wisdar-auth@outlook.com'
